In [6]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [21]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/WeatherPy_challenge.csv")
city_data_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs)
0,Abong Mbang,CM,2020-02-18 05:32:23,3.98,13.18,68.97,93,41,3.29,scattered clouds,0.00,0.0
1,Abonnema,NG,2020-02-18 05:32:23,4.71,6.79,78.69,88,78,2.51,broken clouds,0.00,0.0
2,Abu Dhabi,AE,2020-02-18 05:30:22,24.47,54.37,69.80,49,72,9.17,broken clouds,0.00,0.0
3,Acarau,BR,2020-02-18 05:32:24,-2.89,-40.12,74.91,94,92,2.04,overcast clouds,0.00,0.0
4,Achacachi,BO,2020-02-18 05:32:24,-16.05,-68.68,34.05,80,100,0.67,overcast clouds,0.00,0.0
5,Afsin,TR,2020-02-18 05:32:25,38.25,36.91,18.79,90,35,2.53,scattered clouds,0.00,0.0
6,Ahipara,NZ,2020-02-18 05:32:25,-35.17,173.17,71.92,73,20,4.54,few clouds,0.00,0.0
7,Airai,TL,2020-02-18 05:32:25,-8.93,125.41,80.20,69,41,4.90,light rain,2.81,0.0
8,Aklavik,CA,2020-02-18 05:32:25,68.22,-135.01,-23.80,74,5,5.82,clear sky,0.00,0.0
9,Albany,US,2020-02-18 05:29:18,42.60,-73.97,27.00,58,90,4.70,overcast clouds,0.00,0.0

In [22]:
city_data_df = city_data_df.dropna(how='any')
city_data_df.isna().sum()

City                      0
Country                   0
Date                      0
Lat                       0
Lng                       0
Max Temp                  0
Humidity                  0
Cloudiness                0
Wind Speed                0
Current Description       0
Rain inches(last 3hrs)    0
Snow inches(last 3hrs)    0
dtype: int64

In [23]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))
# Ask if the customer is okay with rain or snow
is_raining = True if input("Do you want it to be raining? (yes/no) ").lower()=="yes" else False
is_snowing = True if input("Do you want it to be snowing? (yes/no) ").lower()=="yes" else False

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 100
Do you want it to be raining? (yes/no) yes
Do you want it to be snowing? (yes/no) yes

In [24]:
# Create data filer condition
condition_filter =(city_data_df["Max Temp"]>=min_temp)&(city_data_df["Max Temp"]<=max_temp)
# declare a parameter to keep condition of rain or snow
rain_or_snow_filter=None

#the customer want it to be raining
if is_raining:
    rain_or_snow_filter = city_data_df["Rain inches(last 3hrs)"]>0
else:
    rain_or_snow_filter = city_data_df["Rain inches(last 3hrs)"]==0

#the customer want it to be snowing
if is_snowing:
    rain_or_snow_filter = rain_or_snow_filter | (city_data_df["Snow inches(last 3hrs)"]>0)
else:
    rain_or_snow_filter = rain_or_snow_filter | (city_data_df["Snow inches(last 3hrs)"]==0)

#combine filter
condition_filter = condition_filter & rain_or_snow_filter

In [28]:
#Query the dataframe with the customer prefers
preferred_cities_df = city_data_df.loc[condition_filter]
preferred_cities_df.head(10)

,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches(last 3hrs),Snow inches(last 3hrs)
7,Airai,TL,2020-02-18 05:32:25,-8.93,125.41,80.20,69,41,4.90,light rain,2.81,0.00
21,Aripuana,BR,2020-02-18 05:32:28,-9.17,-60.63,73.69,98,45,1.72,light rain,1.63,0.00
30,Auki,SB,2020-02-18 05:32:30,-8.77,160.70,84.78,73,100,21.34,light rain,0.38,0.00
31,Avarua,CK,2020-02-18 05:32:09,-21.21,-159.78,80.60,88,100,17.22,moderate rain,4.19,0.00
33,Balaipungut,ID,2020-02-18 05:32:31,1.05,101.28,83.34,82,100,2.64,moderate rain,5.25,0.00
36,Bandarbeyla,SO,2020-02-18 05:32:31,9.49,50.81,78.26,74,72,12.21,light rain,0.13,0.00
50,Bengkulu,ID,2020-02-18 05:32:35,-3.80,102.27,83.80,71,74,3.06,light rain,0.63,0.00
56,Bima,ID,2020-02-18 05:32:36,-8.47,118.72,80.64,85,100,1.39,moderate rain,5.63,0.00
59,Bizhbulyak,RU,2020-02-18 05:32:36,53.70,54.26,27.77,90,100,23.55,light snow,0.00,0.38
64,Borba,BR,2020-02-18 05:32:38,-4.39,-59.59,74.61,97,55,1.34,light rain,0.56,0.00

In [26]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp","Current Description", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
7,Airai,TL,80.20,light rain,-8.93,125.41,
21,Aripuana,BR,73.69,light rain,-9.17,-60.63,
30,Auki,SB,84.78,light rain,-8.77,160.70,
31,Avarua,CK,80.60,moderate rain,-21.21,-159.78,
33,Balaipungut,ID,83.34,moderate rain,1.05,101.28,
36,Bandarbeyla,SO,78.26,light rain,9.49,50.81,
50,Bengkulu,ID,83.80,light rain,-3.80,102.27,
56,Bima,ID,80.64,moderate rain,-8.47,118.72,
59,Bizhbulyak,RU,27.77,light snow,53.70,54.26,
64,Borba,BR,74.61,light rain,-4.39,-59.59,

In [8]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [26]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [34]:
#Save to file without index column
hotel_df.to_csv("weather_data/WeatherPy_vacation.csv",index=False)
# display head 10
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
7,Airai,TL,80.20,light rain,-8.93,125.41,Juvinal Martin
21,Aripuana,BR,73.69,light rain,-9.17,-60.63,
30,Auki,SB,84.78,light rain,-8.77,160.70,Auki Motel
31,Avarua,CK,80.60,moderate rain,-21.21,-159.78,Paradise Inn
33,Balaipungut,ID,83.34,moderate rain,1.05,101.28,Swee Ann Homestay
36,Bandarbeyla,SO,78.26,light rain,9.49,50.81,REER XOOSHLE GROUP
50,Bengkulu,ID,83.80,light rain,-3.80,102.27,Grage Hotel Bengkulu
56,Bima,ID,80.64,moderate rain,-8.47,118.72,Lambitu Hotel
59,Bizhbulyak,RU,27.77,light snow,53.70,54.26,Монумент дружбы
64,Borba,BR,74.61,light rain,-4.39,-59.59,Hotel da Amazônia

In [28]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [29]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
#max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, \
#             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

In [31]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [33]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
#max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
#             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))